version: '2.2'
services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        privileged: true
        user: root
        ports:
            - 8080:8080
            - 50000:50000
        restart: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - $HOME/jenkinss:/var/jenkins_home 
          - $HOME/jenkinss:/var/jenkins_home/downloads 
          - /usr/bin/docker:/usr/bin/docker 
